export const START_CHATING = 'START_CHATING';
export const SENT_MSG = 'SENT_MSG';
export const SET_USER = 'SET_USER';
export const REPLY_MSG = 'REPLY_MSG';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const GROUP_MSG = 'GROUP_MSG';
export const CONTACT_MSG = 'CONTACT_MSG';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS';
export const LOAD_ALL_USERS = 'LOAD_ALL_USERS';

export const ADD_CONVERSATION = 'ADD_CONVERSATION';
export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';

// Presence / online status
export const UPDATE_PRESENCE = 'UPDATE_PRESENCE';
export const UPDATE_USER_ONLINE_STATUS = 'UPDATE_USER_ONLINE_STATUS';
export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS';

// Incoming call
export const SET_INCOMING_CALL = 'SET_INCOMING_CALL';
export const CLEAR_INCOMING_CALL = 'CLEAR_INCOMING_CALL';
export const CALL_ACCEPTED_BY_RECIPIENT = 'CALL_ACCEPTED_BY_RECIPIENT';
export const CALL_DECLINED_BY_RECIPIENT = 'CALL_DECLINED_BY_RECIPIENT';
export const CALL_ENDED = 'CALL_ENDED';

export const CLEAR_UNREAD = 'CLEAR_UNREAD';

// Reply
export const SET_REPLY = 'SET_REPLY';
export const CLEAR_REPLY = 'CLEAR_REPLY';
